name: 打包vue项目
on: push

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest
    
    steps:
      - name: 检查仓库内容
        uses: actions/checkout@v4
      
      - name: 库安装
        run: npm install
      
      - name: 打包
        run: npm run build

